
services:
  web:
    build:
      context: .
    volumes:
      - ./django_telegrambot_converter/:/app
    ports:
      - 8080:8080
    command: "python manage.py runserver 0.0.0.0:8080"

  bot:
    build:
      context: .
    volumes:
      - ./django_telegrambot_converter/:/app
    command: "python manage.py start_bot"

  celery_worker:
    build:
      context: .
    volumes:
      - ./django_telegrambot_converter/:/app
    command: celery -A django_telegrambot_converter worker --loglevel=info
    depends_on:
      - web
      - redis

  celery_beat:
    build:
      context: .
    volumes:
      - ./django_telegrambot_converter/:/app
    command: celery -A django_telegrambot_converter beat --loglevel=info
    depends_on:
      - web
      - redis

  redis:
      image: redis:alpine
      ports:
        - "6379:6379"