# Generated by Django 5.1.1 on 2024-10-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_profile_delete_telegramuser_message_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
