# Generated by Django 5.1.1 on 2025-02-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency',
            new_name='code',
        ),
    ]
