# Generated by Django 5.1.1 on 2025-02-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_currency_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='code',
        ),
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(default=1, max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
