# Generated by Django 5.1.1 on 2025-02-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_currency_code_currency_name_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_from',
            field=models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
    ]
