# Generated by Django 5.1.1 on 2025-02-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rate_currency_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='core.currency'),
        ),
    ]
