# Generated by Django 5.1.1 on 2025-02-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_rate_currency_from_alter_rate_currency_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_to',
            field=models.CharField(max_length=3),
        ),
    ]
